---
- name: Listing all topologies
  command: "{{ storm_binary }} list"
  remote_user: "{{ user }}"
  become: yes
  become_user: root
  register: list_toplogies

- name: Killing the topology
  command: "{{ storm_binary }} kill {{ topology_name }}"
  when: (list_toplogies.stdout_lines|last != "No topologies running.") and
        (list_toplogies.stdout.find('{{ topology_name }}') != -1)
  remote_user: "{{ user }}"
  become: yes
  become_user: root

- name: Restarting Apache Storm Supervisor
  supervisorctl: name=storm-supervisor state=restarted
  remote_user: "{{ user }}"
  become: yes
  become_user: root
